### ISSUE TITLE
No VNC option

### ISSUE THREAD

**Issue by fede843** [jlesage/docker-baseimage-gui#103]
Hello, I am using an image based on this one. Not fully understand yet how WEB and VNC are related (if they are).
If they are not, is it posible then to disable all VPN logic/services running? I am only interested on accessing the service via a web broswer.

**Comment by jlesage** [comment]
In all cases, the UI of the app is provided via VNC.  When using the WEB interface, the browser is actually running an HTML VNC client.

If you are running the container with the default bridge network, then you can just expose port `5800`.  If port `5900` not exposed, then "normal" VNC clients won't be able to connect.

You can also set the `VNC_LISTENING_PORT` environment variable to `-1` to disable listening on the VNC port for "normal" VNC clients.
