### ISSUE TITLE
[BUG] VNC_PASSWORD binary not found in ubuntu 20.04 upper version 4

### ISSUE THREAD

**Issue by ElGranLoky** [jlesage/docker-baseimage-gui#104]
Docker version with ubuntu 20.04 upper version 4

When setup VNC_PASSWORD and start a container it failed with

[cont-init   ] 10-vnc-password.sh: /etc/cont-init.d/10-vnc-password.sh: 26: /opt/tigervnc/bin/vncpasswd: not found

In the file rootfs/etc/cont-init.d/10-vnc-password.sh line 26 is

VNCPASSWD_BIN=/opt/base/bin/vncpasswd

but if i find / -name vncpasswd only show in the path

/usr/tigervnc/bin/vncpasswd

Sorry for the fast typing.

**Comment by jlesage** [comment]
What version are you using exactly?  According to the log message you provided, you are using an old version.

`/opt/base/bin/vncpasswd` is the correct path:

```
$ docker run --rm jlesage/baseimage-gui:ubuntu-20.04-v4.4.1 ls -l /opt/base/bin/vncpasswd
-rwxr-xr-x 1 root root 72408 Apr 16 16:23 /opt/base/bin/vncpasswd
```

**Comment by ElGranLoky** [comment]
Sorry I test only version 4.0
