### ISSUE TITLE
Buttons for additional windows

### ISSUE THREAD

**Issue by konradb90** [jlesage/docker-baseimage-gui#105]
I work with JAVA applets that run in full window mode. This is the correct behavior. 

JAVA applets also have a virtual keyboard mechanism, which we can enable from the options menu. In the docker container it looks like this: https://gyazo.com/caeb39e001ae333971659e55997ee789

I would like to include navigation buttons for additional windows to make it look like this: https://gyazo.com/e634d47f24c03cf4920a88469d1aa76a

Is it possible?

**Comment by konradb90** [comment]
I solved this by adding a simple script:

```
sed -i 's/<decor>no/<decor>yes/' /etc/X11/openbox/rc.xml
openbox --restart
```

Perhaps there is a better solution that you can recommend ;)

**Comment by jlesage** [comment]
Looks like you need to properly identify the main window.  See:
https://github.com/jlesage/docker-baseimage-gui#maximizing-only-the-main-window

**Comment by konradb90** [comment]
Unfortunately, this solution does not work. Both windows (main and virtual keyboard) have exactly the same parameters (name, type, etc.). Decoration in this case is disabled regardless of which window I choose.

**Comment by jlesage** [comment]
If you are sure that all `_OB_APP*` properties are the same, then there is no way for the window manager (openbox) to apply different settings for each window.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
