### ISSUE TITLE
fail to run example

### ISSUE THREAD

**Issue by marcmk6** [jlesage/docker-baseimage-gui#106]
Hi,

I copied the xterm example (both Dockerfile and startapp.sh) but it failed to run.
I got `[app         ] /!\ No application to start: /startapp.sh is missing or not executable. /!\` and everything quits.
What are possible reasons?

**Comment by jlesage** [comment]
Did you create `startapp.sh` with execution permission ?

**Comment by marcmk6** [comment]
thanks the problem was the execution permission.
