### ISSUE TITLE
Ubuntu 18.04 LTS image?

### ISSUE THREAD

**Issue by ualex73** [jlesage/docker-baseimage-gui#11]
Is there any plan to release a Ubuntu 18.04 LTs release of this handy baseimage-gui?

**Comment by jlesage** [comment]
Yes, I'm working on this and it should be available soon :)

**Comment by ualex73** [comment]
Thanks :+1:

**Comment by jlesage** [comment]
Image for Ubuntu 18.04 now available.

**Comment by ualex73** [comment]
The 18.04 is not available on docker yet?

**Comment by jlesage** [comment]
You are right, docker hub didn't build the image based on 18.04.
I'm working on this.

**Comment by jlesage** [comment]
Image is now available.

**Comment by ualex73** [comment]
Thanks, testing with it now :+1:
