### ISSUE TITLE
Failed to connect to socket /var/run/dbus/system_bus_socket

### ISSUE THREAD

**Issue by Loader23** [jlesage/docker-baseimage-gui#114]
Hi,

I tried to upgrade [this ](https://github.com/acaranta/docker-joplin/tree/master) from ubuntu-18.04 to ubuntu-18.04-v4 but I always get this Error:
Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket

I have also tried with 22.04 and Debian but the error stays the same.
Any advise?

**Comment by jlesage** [comment]
Which component is giving this error ?

**Comment by Loader23** [comment]
Is this what you are looking for?:
```
[app         ] [778:1106/072547.484384:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[app         ] LaunchProcess: failed to execvp:
[app         ] xdg-settings
[supervisor  ] service 'app' exited (got signal SIGILL).
[supervisor  ] restarting service 'app'.
[supervisor  ] starting service 'app'...
```

**Comment by jlesage** [comment]
Ok so the issue is with Joplin itself ?
Also, is the issue really when changing from ubuntu-18.04 to ubuntu-18.04-v4 ?  Or it's just the update to the latest Joplin version that cause the problem ?

**Comment by Loader23** [comment]
The dockerfile always downloads the latest Joplin version. I forgot to mention that I had to add libfuse2 dependency, but thats for both versions - 18.04 and 18.04-v2.
But the issue really occurs when changing from 18.04 to 18.04-v4. Joplin does not start anymore with the new Image.

Here is the working dockerfile:
```
FROM jlesage/baseimage-gui:ubuntu-18.04

RUN apt-get update && apt-get install -y wget libnss3 libgtk-3-0 libxss1 libasound2 libgbm1 libfuse2
RUN useradd --shell /sbin/nologin --home /app --uid 1000  -G users appuser
RUN mkdir /app && chown appuser -Rfv /app
USER appuser
RUN echo $USER
WORKDIR /app
RUN wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh >/app/install-joplin.sh && chmod +x /app/install-joplin.sh
RUN TERM=xterm /app/install-joplin.sh --allow-root --force
RUN /app/.joplin/Joplin.AppImage --appimage-extract
ENV APPDIR=/app/squashfs-root
ADD startapp.sh /startapp.sh
USER root
ADD https://raw.githubusercontent.com/laurent22/joplin/dev/Assets/LinuxIcons/256x256.png /app/joplin-logo.png
RUN APP_ICON_URL=file:///app/joplin-logo.png && install_app_icon.sh "$APP_ICON_URL"
ENV APP_NAME="Joplin"
```
And the Startapp.sh, just for completion.
```
#!/bin/sh
cd /app
USER=appuser 
HOME="/app"
exec /app/squashfs-root/AppRun --no-sandbox
```

Now changing 18.04 to 18.04-v4 will cause the error above.

**Comment by jlesage** [comment]
Maybe you need to install additional packages with v4 ?
I would check what packages are installed when using 18.04 and then compare with 18.04-v4.

**Comment by Loader23** [comment]
You mean the packages which are installed at building the image? So, I should look at the building process and compare or whats the best way?
I hoped you could say whats the difference between 18.04 and 18.04-v4 is. :-)

**Comment by jlesage** [comment]
You are welcome!
