### ISSUE TITLE
32bit or i386 version.

### ISSUE THREAD

**Issue by jokomad** [jlesage/docker-baseimage-gui#116]
Are there any? And how to use them...

on dockerhub it states that there is a linux/386 version but i do not know how to select it in dockerfile...

FROM jlesage/baseimage-gui:alpine-3.15-v4...

**Comment by jlesage** [comment]
The baseimage is multi-arch.  This means that the correct version will be selected depending on the arch of the machine from which you run `docker build`.

If you want to build for a different arch, then you need to use buildx: https://docs.docker.com/engine/reference/commandline/buildx_build/

**Comment by jokomad** [comment]
Thank you. Found it. Example for newbies like me:

FROM --platform=linux/386 jlesage/baseimage-gui:debian-11-v4.5

**Comment by jlesage** [comment]
You are right, that's another way.
