### ISSUE TITLE
[Feature Request] Add image based on debian-slim

### ISSUE THREAD

**Issue by dinana** [jlesage/docker-baseimage-gui#119]
Would it be possible to add an image based on debian-slim? Alpine is minimal but is challenging due to it's use of musl

**Comment by jlesage** [comment]
Yes, there are already images based on debian 10 and 11.

https://github.com/jlesage/docker-baseimage-gui#images

**Comment by jlesage** [comment]
Closing this issue. Please re-open if needed.
