### ISSUE TITLE
Question: maximise only main window

### ISSUE THREAD

**Issue by sunyi000** [jlesage/docker-baseimage-gui#125]
I tried to follow the section Maximizing Only the Main Window.

I started the container, and I can see the application is running in browser.

`docker exec [container] obxprop |grep "^_OB_APP" ` gives error about unable to connect to X display

I also tried to exec into the running container, there's no /etc/openbox directory

I'm using the image jlesage/baseimage-gui:ubuntu-22.04-v4.5.2

Thanks for any help

**Comment by jlesage** [comment]
Humm looks like for the ubuntu version not all the environment variables are present when running command.

As a workaround, you can login to the container with `docker exec [container] sh` and then run from there `obxprop | grep "^_OB_APP"`

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
