### ISSUE TITLE
Change the time until the SIGKILL signal.

### ISSUE THREAD

**Issue by Roalkege** [jlesage/docker-baseimage-gui#126]
> After 5 seconds, all remaining processes are forcefully terminated via the SIGKILL signal.

Is it possible to change the time until the SIGKILL signal? 5 seconds isn't enough for my use case. Sometimes this corrupts data.

**Comment by jlesage** [comment]
This is currently not configurable per service, but I will look at this.  This is a good feature.

Note however that if the container takes too long to terminate by itself, Docker will forcefully do it.

**Comment by jlesage** [comment]
Now implemented with the latest version of the baseimage via the `SERVICES_GRACETIME` environment variable.
