### ISSUE TITLE
The system shuts down right after the start

### ISSUE THREAD

**Issue by SoerenSofke** [jlesage/docker-baseimage-gui#13]
I am using Docker (Version 2.0.0.0-win81 (29211)) on Windows 10. Following exactly your example "Getting started" provided in README.md, I got the following log, mentioning "s6-applyuidgid: fatal: unable to exec /startapp.sh: No such file or directory":

C:\Users\Sofke\Desktop\dockerGui>docker build -t docker-xterm .
Sending build context to Docker daemon   5.12kB
Step 1/4 : FROM jlesage/baseimage-gui:alpine-3.6
 ---> 03c81ba1677f
Step 2/4 : RUN add-pkg xterm
 ---> Using cache
 ---> b8433a4f4a96
Step 3/4 : COPY startapp.sh /startapp.sh
 ---> 3ba17dfd408f
Step 4/4 : ENV APP_NAME="Xterm"
 ---> Running in c3d4798cc140
Removing intermediate container c3d4798cc140
 ---> 37268c153245
Successfully built 37268c153245
Successfully tagged docker-xterm:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

C:\Users\Sofke\Desktop\dockerGui>docker run --rm -p 5800:5800 -p 5900:5900 docker-xterm
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting xvfb...
[xvfb] starting...
[services.d] starting openbox...
[openbox] starting...
Openbox-Message: Openbox was compiled without image loading support. Icons in menus will not be loaded.
[services.d] starting certsmonitor...
[services.d] starting logmonitor...
[services.d] starting nginx...
[logmonitor] no file to monitor: disabling service...
[certsmonitor] disabling service: secure connection not enabled.
[services.d] starting statusmonitor...
[nginx] starting...
[services.d] starting x11vnc...
[statusmonitor] no file to monitor: disabling service...
[x11vnc] starting...
[services.d] starting app...
14/12/2018 20:36:41 passing arg to libvncserver: -rfbport
14/12/2018 20:36:41 passing arg to libvncserver: 5900
14/12/2018 20:36:41 passing arg to libvncserver: -rfbportv6
14/12/2018 20:36:41 passing arg to libvncserver: -1
14/12/2018 20:36:41 passing arg to libvncserver: -httpportv6
14/12/2018 20:36:41 passing arg to libvncserver: -1
14/12/2018 20:36:41 passing arg to libvncserver: -desktop
14/12/2018 20:36:41 passing arg to libvncserver: Xterm
[app] starting Xterm...
14/12/2018 20:36:41 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 749
s6-applyuidgid: fatal: unable to exec /startapp.sh: No such file or directory
14/12/2018 20:36:41 Using X display :0
14/12/2018 20:36:41 rootwin: 0x43 reswin: 0x400001 dpy: 0x35eea00
14/12/2018 20:36:41
14/12/2018 20:36:41 ------------------ USEFUL INFORMATION ------------------
[services.d] done.
14/12/2018 20:36:41 X DAMAGE available on display, using it for polling hints.
14/12/2018 20:36:41   To disable this behavior use: '-noxdamage'
14/12/2018 20:36:41
14/12/2018 20:36:41   Most compositing window managers like 'compiz' or 'beryl'
14/12/2018 20:36:41   cause X DAMAGE to fail, and so you may not see any screen
14/12/2018 20:36:41   updates via VNC.  Either disable 'compiz' (recommended) or
14/12/2018 20:36:41   supply the x11vnc '-noxdamage' command line option.
14/12/2018 20:36:41 X COMPOSITE available on display, using it for window polling.
14/12/2018 20:36:41   To disable this behavior use: '-noxcomposite'
14/12/2018 20:36:41
14/12/2018 20:36:41 Wireframing: -wireframe mode is in effect for window moves.
14/12/2018 20:36:41   If this yields undesired behavior (poor response, painting
14/12/2018 20:36:41   errors, etc) it may be disabled:
14/12/2018 20:36:41    - use '-nowf' to disable wireframing completely.
14/12/2018 20:36:41    - use '-nowcr' to disable the Copy Rectangle after the
14/12/2018 20:36:41      moved window is released in the new position.
14/12/2018 20:36:41   Also see the -help entry for tuning parameters.
14/12/2018 20:36:41   You can press 3 Alt_L's (Left "Alt" key) in a row to
14/12/2018 20:36:41   repaint the screen, also see the -fixscreen option for
14/12/2018 20:36:41   periodic repaints.
14/12/2018 20:36:41 GrabServer control via XTEST.
14/12/2018 20:36:41
14/12/2018 20:36:41 Scroll Detection: -scrollcopyrect mode is in effect to
14/12/2018 20:36:41   use RECORD extension to try to detect scrolling windows
14/12/2018 20:36:41   (induced by either user keystroke or mouse input).
14/12/2018 20:36:41   If this yields undesired behavior (poor response, painting
14/12/2018 20:36:41   errors, etc) it may be disabled via: '-noscr'
14/12/2018 20:36:41   Also see the -help entry for tuning parameters.
14/12/2018 20:36:41   You can press 3 Alt_L's (Left "Alt" key) in a row to
14/12/2018 20:36:41   repaint the screen, also see the -fixscreen option for
14/12/2018 20:36:41   periodic repaints.
14/12/2018 20:36:41
14/12/2018 20:36:41 XKEYBOARD: number of keysyms per keycode 7 is greater
14/12/2018 20:36:41   than 4 and 51 keysyms are mapped above 4.
14/12/2018 20:36:41   Automatically switching to -xkb mode.
14/12/2018 20:36:41   If this makes the key mapping worse you can
14/12/2018 20:36:41   disable it with the "-noxkb" option.
14/12/2018 20:36:41   Also, remember "-remap DEAD" for accenting characters.
14/12/2018 20:36:41
14/12/2018 20:36:41 X FBPM extension not supported.
14/12/2018 20:36:41 X display is not capable of DPMS.
14/12/2018 20:36:41 --------------------------------------------------------
14/12/2018 20:36:41
14/12/2018 20:36:41 Default visual ID: 0x21
[services.d] stopping services
14/12/2018 20:36:41 Read initial data from X display into framebuffer.
14/12/2018 20:36:41 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
14/12/2018 20:36:41
14/12/2018 20:36:41 X display :0 is 32bpp depth=24 true color
14/12/2018 20:36:41
14/12/2018 20:36:41 Listening for VNC connections on TCP port 5900
14/12/2018 20:36:41
14/12/2018 20:36:41 Xinerama is present and active (e.g. multi-head).
14/12/2018 20:36:41 Xinerama: number of sub-screens: 1
14/12/2018 20:36:41 Xinerama: no blackouts needed (only one sub-screen)
14/12/2018 20:36:41
14/12/2018 20:36:41 fb read rate: 1851 MB/sec
14/12/2018 20:36:41 fast read: reset -wait  ms to: 10
14/12/2018 20:36:41 fast read: reset -defer ms to: 10
14/12/2018 20:36:41 The X server says there are 10 mouse buttons.
14/12/2018 20:36:41 screen setup finished.
14/12/2018 20:36:41

The VNC desktop is:      94c38ecbd105:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
14/12/2018 20:36:41 deleted 40 tile_row polling images.
[services.d] stopping statusmonitor...
[services.d] stopping nginx...
[services.d] stopping logmonitor...
[services.d] stopping certsmonitor...
[services.d] stopping openbox...
[services.d] stopping xvfb...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by soerensofke** [comment]
Issue solved:

line ending set to UNIX-format (LF) instead of Windows (CR LF)

Great Docker image!

**Comment by furritos** [comment]
Using `dos2unix` in Windows 10 - Ubuntu works well
