### ISSUE TITLE
Request for debian-12 / bookworm baseimage-gui support

### ISSUE THREAD

**Issue by bontebok** [jlesage/docker-baseimage-gui#133]
Greetings,

Thanks for building this awesome project. I have tried, and failed to build a bespoke one for debian-12 and failed miserably. I would to support running the latest version of some packages that are distributed in debian-12 and would love to use them out of the box without having to port/compile them back to debian-11.

If it's not too difficult of a task, would you consider adding debian-12 support to your baseimage-gui Docker image?

Thanks!
Rucio

**Comment by jlesage** [comment]
Yes, I will add it!

**Comment by jlesage** [comment]
Added in version 4.6.4.
