### ISSUE TITLE
Favicons referenced using absolute paths

### ISSUE THREAD

**Issue by 2xSSgETh2ce4** [jlesage/docker-baseimage-gui#14]
Favicons are referenced using absolute paths (i.e. /images/icons/...)

All other resources in /opt/novnc/index.vnc are referenced using relative paths (i.e. js/..., css/..., etc).

Referencing resources via absolute paths breaks the application when it is running behind a reverse proxy using path based routing (i.e.   http://server/appname/  -->  http://realserver/).

This issue is affecting the 'jlesage/docker-handbrake' project, but as the script that installs the favicons exists in this project (i.e. /usr/local/bin/install_app_icon.sh), I am filing the issue here.

**Comment by jlesage** [comment]
Fixed with version 4.0.3.
