### ISSUE TITLE
htpasswd - The requested URL returned error: 404

### ISSUE THREAD

**Issue by NeoCortex3** [jlesage/docker-baseimage-gui#140]
Hi there, I'm trying to build a simple xterm docker image.

In "Dockerfile" I set:

```
#syntax=docker/dockerfile:1.4
#baseimage-gui Dockerfile
#https://github.com/jlesage/docker-baseimage-gui

ARG BASEIMAGE=jlesage/baseimage-gui:alpine-3.19-v4
```

and at the end of the file:

```
RUN add-pkg xterm font-dejavu python3
COPY startapp.sh /startapp.sh
RUN set-cont-env APP_NAME "Xterm"
```

(by the way how do I know the versions of an baseimage? alpine-3.20-v1 gave an error)

Now, when I try "Docker build -t docker-xterm ." I get the error:

```
(...)
51.65 (86/91) Installing libedit (20240517.3.1-r0)
51.67 (87/91) Installing libedit-dev (20240517.3.1-r0)
51.70 (88/91) Installing libpcre2-16 (10.43-r0)
51.73 (89/91) Installing libpcre2-32 (10.43-r0)
51.81 (90/91) Installing pcre2-dev (10.43-r0)
52.08 (91/91) Installing util-linux-static (2.40.1-r1)
56.62 OK: 573 MiB in 143 packages
56.76 >>> Downloading httpd...
56.84 curl: (22) The requested URL returned error: 404
56.84
56.85 tar: invalid magic
56.85 tar: short read
------
Dockerfile:183
--------------------
 181 |     COPY --from=xx / /
 182 |     COPY src/htpasswd /tmp/build-htpasswd
 183 | >>> RUN /tmp/build-htpasswd/build.sh
 184 |     RUN xx-verify --static /tmp/httpd-install/usr/bin/htpasswd
 185 |     COPY --from=upx /usr/bin/upx /usr/bin/upx
--------------------
ERROR: failed to solve: process "/bin/sh -c /tmp/build-htpasswd/build.sh" did not complete successfully: exit code: 1
```

To me it looks like the download for htpasswd just 404ed... anything I can do about this?

Thanks,
Julix

**Comment by jlesage** [comment]
It looks like you have something else in your Dockerfile, or you are not building from the correct directory ?

**Comment by NeoCortex3** [comment]
![image](https://github.com/user-attachments/assets/13029810-e125-43f8-a8b9-7dfa297a2836)

This is my directory /Docker_Compose/aniworld_scraper/

This https://pastebin.com/J8cNGkSc is my complete "Dockerfile" only change I made is at the start "arg baseimage" and

```
RUN add-pkg xterm font-dejavu python3
COPY startapp.sh /startapp.sh
RUN set-cont-env APP_NAME "Xterm"
```

at the end of the file.

**Comment by NeoCortex3** [comment]
I have taken a look at the scripts.

In "/src/htpasswd/build.sh" we have

```
# Define software versions.
HTTPD_VERSION=2.4.59

# Define software download URLs.
HTTPD_URL=https://dlcdn.apache.org/httpd/httpd-${HTTPD_VERSION}.tar.gz
```
 which will resolve to: https://dlcdn.apache.org/httpd/httpd-2.4.59.tar.gz

which indeed 404ed.

**Comment by jlesage** [comment]
If you want to build your own app, follow the steps indicated at https://github.com/jlesage/docker-baseimage-gui?tab=readme-ov-file#getting-started.

You need to do this in a new directory, otherwise you are building the baseimage itself instead of your app.

**Comment by NeoCortex3** [comment]
In "/src/pulseaudio/build.sh"

we got
```
# Define software versions.
PULSEAUDIO_VERSION=16.1
LIBSNDFILE_VERSION=1.2.2

# Define software download URLs.
PULSEAUDIO_URL=https://freedesktop.org/software/pulseaudio/releases/pulseaudio-${PULSEAUDIO_VERSION}.tar.xz
LIBSNDFILE_URL=https://github.com/libsndfile/libsndfile/releases/download/${LIBSNDFILE_VERSION}/libsndfile-${LIBSNDFILE_VERSION}.tar.xz
```

which will resolve to https://freedesktop.org/software/pulseaudio/releases/pulseaudio-16.1.tar.xz
which gives a certificate error if you try to visit it.
disabling ssl/tls in "/src/pulseaudio/build.sh" on line 93 with the -k parameter did not work.
`curl -# -k -L -f ${PULSEAUDIO_URL} | tar -xJ --strip 1 -C /tmp/pulseaudio`

Will have to give this another look tomorrow.

**Comment by sgpublic** [comment]
> which gives a certificate error if you try to visit it.

Yes, based on the latest commit, if you want to build successfully, you need to make the following changes:

+ [/src/audiorecorder/build.sh#L16](https://github.com/jlesage/docker-baseimage-gui/blob/f5dc5d646dc5f453141884ad9c6413d14ee86c6a/src/audiorecorder/build.sh#L16)
  ```diff
  - PULSEAUDIO_URL=https://freedesktop.org/software/pulseaudio/releases/pulseaudio-${PULSEAUDIO_VERSION}.tar.xz
  + PULSEAUDIO_URL=https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-${PULSEAUDIO_VERSION}.tar.xz
  ```
+ [/src/pulseaudio/build.sh#L16](https://github.com/jlesage/docker-baseimage-gui/blob/f5dc5d646dc5f453141884ad9c6413d14ee86c6a/src/pulseaudio/build.sh#L16)
  ```diff
  - PULSEAUDIO_URL=https://freedesktop.org/software/pulseaudio/releases/pulseaudio-${PULSEAUDIO_VERSION}.tar.xz
  + PULSEAUDIO_URL=https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-${PULSEAUDIO_VERSION}.tar.xz
  ```
+ [/src/htpasswd/build.sh#L16](https://github.com/jlesage/docker-baseimage-gui/blob/f5dc5d646dc5f453141884ad9c6413d14ee86c6a/src/htpasswd/build.sh#L14)
  ```diff
  - HTTPD_VERSION=2.4.59
  + HTTPD_VERSION=2.4.62
  ```

**Comment by jlesage** [comment]
> I know, but in fact I actualy need an xterm docker-image for some tests.

I'm still not sure why you need to re-build the baseimage. The example of the quick start will give you exactly this.

**Comment by NeoCortex3** [comment]
> > I know, but in fact I actualy need an xterm docker-image for some tests.
> 
> I'm still not sure why you need to re-build the baseimage. The example of the quick start will give you exactly this.

Because I'm gonna reiterrate on it, play around with it, add some own scripts.

Thanks to @sgpublic these changes fix the baseimage and thank you @jlesage for adding them in to quickly.
