### ISSUE TITLE
VNC now, had X11 support?

### ISSUE THREAD

**Issue by jakern** [jlesage/docker-baseimage-gui#142]
I had used the project several years ago now to build a gui application that would connect to the X11 server and display applications locally without a VNC server. I'm now trying to update it and see that the base image now uses VNC. Could you please provide any detail for the change and perhaps the version which this occurred so that I can try to use the old method?

Thank you for your time.

**Comment by jlesage** [comment]
This project always relied on VNC to access the application's UI either via a VNC client or a web browser.

Could you provide more details about which version of the image you were using and how you were using it ?

**Comment by jakern** [comment]
You are right, I apologize. We were using the firefox container from
November 2020 and somehow extended it so that $DISPLAY was set up in such a
way that the application would appear on the desktop, without access to VNC
through the browser. I don't understand it yet but It is on me to find out
what is broken. Thank you for the awesome project.
