### ISSUE TITLE
How to start the openbox window manager as desktop environment, instead of a single application, like xterm?

### ISSUE THREAD

**Issue by emretapci** [jlesage/docker-baseimage-gui#148]
OpenBox is already installed in the image, but I could not find out how it takes which standalone program to start from `startapp.sh`. I want to run a Linux instance in a docker container with a window manager already running.

**Comment by jlesage** [comment]
This project focuses on running a single app. So the OpenBox config has been tweaked for this use case.
If you want to run a full desktop, I would recommend to look at other alternatives. For example, this is a great project: https://docs.linuxserver.io/images/docker-webtop/
