### ISSUE TITLE
new environment variable for port number

### ISSUE THREAD

**Issue by orsomething1030** [jlesage/docker-baseimage-gui#17]
The default port is set to 5800 for all your docker images and the default cannot be changed.  For containers on my normal docker network this is fine since I can remap the ports in the compose file, but if I use a VPN docker network then all containers share the same network interface as the vpn client container.

For instance, the vpn client docker compose file would look something like this:
  vpn_client:
    image: dperson/openvpn-client
        ports:
        #ports for app containers' UI to be reachable from local network
        #firefox
        - "5801:5800"
        #jdownloader
        #- "5802:5800"
        .... etc

and then your docker containers would have in their compose section:
     network_mode: "service:vpn_client"

Since all your docker images share 5800 as the default port, I can't use more than one of them on my VPN docker network.  Please add an environment variable to the base-image to change the default port number to allow cases like this.

**Comment by reedhaffner** [comment]
Same problem here, while using with the realies/soulseek-docker container. Both use 5900 as the internal VNC port, with no option to change it. Would like to see a environment variable like INTERNAL_VNC_PORT.

**Comment by Loader23** [comment]
I have tried several things today but no luck. Mapping a modified default_site.conf with a different port does not work, the container quits with ERROR: No modification applied to /etc/nginx/default_site.conf.
Very frustrating. Maybe @jlesage can give some advice on how to change the default port. 
Workarounds welcome.

**Comment by jlesage** [comment]
The next version of the base image I'm working on will have this functionality.

Note that this is a problem only when creating a container without using the default bridge network.  Else, you can re-map ports using the `-p` parameter of the `docker run` command.

**Comment by jlesage** [comment]
This is now supported with version 4.0.0 of images.
