### ISSUE TITLE
Enable toggling of direct VNC server access.

### ISSUE THREAD

**Issue by r-pufky** [jlesage/docker-baseimage-gui#19]
By default, both ports `5800` and `5900` are exposed in the container. It would be fantastic to be able to add the option toggle the following port exposures:

* 5800 (VNC web GUI only)
* 5900 (VNC server only)
* 5800-5900 (both VNC web GUI, VNC server; current mode)

This would enable the selection of the preferred connection for an end user and minimize service exposure in the container.

**Comment by jlesage** [comment]
When using the default docker network mode `Bridge`, users need to explicitly expose the port(s) they want during the creation of the container.

**Comment by jlesage** [comment]
With images version 4.0.0, it's possible to disable listening on a port.
