### ISSUE TITLE
fail to rebuild base image from Dockerfiles

### ISSUE THREAD

**Issue by Trophime** [jlesage/docker-baseimage-gui#2]
Hi,
I'm trying to rebuild a base image from Dockerfile.debian
It fails because of unknown commands: add-pkg, del-pkg, sed-patch and install-icon...
same for Dockerfile.alpine.

I must have missed something...
Thans for your comments

**Comment by jlesage** [comment]
Are you using the build script?
```
./build.sh debian-8
```

**Comment by Trophime** [comment]
no as I was planning to debian-9 or even debian testing...
I would like to rebuild your image from scratch...

The missing functions are defined somewhere in the "hooks"?

**Comment by jlesage** [comment]
This baseimage is not built from scratch, but depends on another one (`jlesage/baseimage`).  So you need to add support for a new distro in `jlesage/baseimage` first.  You could add a version file in the `versions` directory.

**Comment by Trophime** [comment]
but how is build `jlesage/baseimage`?

**Comment by jlesage** [comment]
Same principle as this one: you have a `build.sh` you can use.
https://github.com/jlesage/docker-baseimage

**Comment by jlesage** [comment]
Closing this issue.
