### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by korzq** [jlesage/docker-baseimage-gui#20]
Hello, I am having difficulty using nginx to reverse proxy. 
```
proxy_pass http://localhost:5800/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header X-Frame-Options SAMEORIGIN;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
}
(ssl)
```
Error: https://hastebin.ericz.me/ahanebodaz.cs
https://eric.is-fi.re/2obsMAg.png

**Comment by jlesage** [comment]
Try a config like described here: https://github.com/jlesage/docker-firefox#reverse-proxy

**Comment by korzq** [comment]
none of the config listed there work

**Comment by jlesage** [comment]
It should.  I know multiple users of different containers using the base image for which this config works.  Maybe you can provide your nginx config to see what's wrong.

**Comment by korzq** [comment]
actually sorry i misread the nginx configs, I’ll try again later today

**Comment by korzq** [comment]
It worked, thanks.
The location i have now is ```
location / {
proxy_pass http://localhost:5800/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_read_timeout 86400;
}
``` and it works fine.
