### ISSUE TITLE
Problem with Qt application

### ISSUE THREAD

**Issue by romancin** [jlesage/docker-baseimage-gui#30]
Hi @jlesage !

I have a problem building my rclonebrowser image, the application only runs on first execution, and since the restart of the container, I only get a black screen. Did you notice problems with Qt applications? Thank you!

**Comment by jlesage** [comment]
I do have some Qt applications that run fine.

If the app runs fine only during the first start, I would check for any files (config) generated by the app that may then interfere.

If you just restart the app (without restarting the container), do you get the same issue ?

**Comment by David-Lor** [comment]
@romancin In my case I created a Bitcoin-Core-GUI image (which is Qt-based) and had no problems so far.

**Comment by romancin** [comment]
Was a problem with the application. Thank you. Closing.
