### ISSUE TITLE
Rebuilding Baseimage: no encryption library could be found

### ISSUE THREAD

**Issue by shiomax** [jlesage/docker-baseimage-gui#31]
I´m trying to rebuild the baseimage for debian9 (arm) and debian10 (amd64 & arm) also did debian9 amd64 now. SSL does not work for VNC. I´m getting this error somewhere in the logs

```
==========================================================================
*** No encryption library could be found. ***
A libvncserver/libvncclient built this way will not support SSL encryption.
To enable SSL install the necessary development packages (perhaps it is named
something like libssl-dev or gnutls-dev) and run configure again.
==========================================================================
```

The test for it is also failing
```

Checking availability of VNC SSL port 5900...
   (in test file tests/test_secure_port_availability.bats, line 33)
     `(( TIMEOUT > 0 ))' failed
   Starting docker container...
   Stopping docker container...
   1fc896a668cd3a6b6b03e701372aa876debf76b19a417e622c2b64a36099e7d7
   Removing docker container...
   1fc896a668cd3a6b6b03e701372aa876debf76b19a417e622c2b64a36099e7d7
```
Are you getting the same error, or am I doing something wrong?

**Comment by jlesage** [comment]
This message in compilation logs is expected and is not a problem.

For the failing test, I would recommend you try to manually launch the container to see what's happening.

Note that I didn't try yet to compile on other architecture than x86_64.

**Comment by shiomax** [comment]
> This message in compilation logs is expected and is not a problem.
> 
> For the failing test, I would recommend you try to manually launch the container to see what's happening.

Thank's for the information. I'll try that. It seemed to me like the failing test is a result of that message.

 

> Note that I didn't try yet to compile on other architecture than x86_64.

That's kinda why I built debian9 x64 now to start with. On debian10 you need to install npm explicitly, nodejs no longer installs npm with it. But then it at least builds. Gonna take some time until I figured everything out. The program I've built a container for (jriver) will eventually move to debian10 dependencies and will no longer work on debian9 and ubuntu18.04. You'll need at least debian10 or ubuntu-19. It's not gonna happen immidiately. But when it does I want to have the debian-10 image done. And I figured while I'm at it I might as well try to build it for arm.

**Comment by shiomax** [comment]
What I said about npm not installing seems to only be happening because nodejs 8.x is not supported by the version of npm that it would install. You can force install it and that works. But updating to nodejs 12.x seems like the cleaner solution. I did that now. Still some testing that needs to be done. But initially debian10 seems to just work.
