### ISSUE TITLE
docker image tags

### ISSUE THREAD

**Issue by djaydev** [jlesage/docker-baseimage-gui#33]
Hi,
So far I've been using the docker tags "jlesage/baseimage-gui:alpine-3.10" without the version number on the end, but with the new alpine-3.11 the available tags all have "v" "number" at the end.  Just asking if that's your new standard going forward? No problem if so, I can update all my dockerfiles to comply with the new tags.
thanks

**Comment by jlesage** [comment]
Hi, this is a mistake, I will add the missing tags.

**Comment by djaydev** [comment]
ok thanks
