### ISSUE TITLE
ARM64 Build

### ISSUE THREAD

**Issue by cristiangauma** [jlesage/docker-baseimage-gui#35]
Hello,

is there any plan to create ARM64v8 images of this project?. 

They are only amd64 as far as I've seen and it would be useful for all of us having Raspberry Pi 4 (or clusters of it).

Thank you!

**Comment by fabiosoft** [comment]
Any news?

**Comment by joelcarlton** [comment]
Any word on an arm64 build? @jlesage

**Comment by jlesage** [comment]
Yes, work still in progress!

**Comment by sshuangliu** [comment]
Need ARM32 V7 as well

**Comment by jlesage** [comment]
Images version 4.0.0 are now multi-arch.
