### ISSUE TITLE
Fails to rebuild baseimage-gui:ubuntu-16.0.4

### ISSUE THREAD

**Issue by bourgeoa** [jlesage/docker-baseimage-gui#4]
I tried to build a baseimage-gui for ubuntu 14.04 to be able to use Ivideon with gui on my synology NAS.
(it does not work on ubuntu 16.04)

Not succeeding I went to try to rebuild the baseimage-gui:ubuntu-16.04-v3.3.5 
I followed the full build process basimage ./build.sh ubuntu-16.04 then baseimage-gui idem 
- in baseimage build curl curl no URL (idem for basimage-gui) (docker version 17.0.5.0-ce)
  solved transforming ARG xxx_URL in ENV xxx_URL
- bats not available (I don't know how to install it on Synoloy)
- basimage-16.0.4 finally built. It seems working I tried to build the xterm exemple. It stopped because of no display, but seems to work correctly

Then build of baseimage-gui
- I also had to to change a few ARG in ENV
- I have a lot of build errors
    - a few of these 
"invoke-rc.d: policy-rc.d denied execution of start."
    - and of these 
"npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field."

At the end an image is build but when I use it (xterm exemple) it doesn't work (docker build OK) and docker run start and immediately stop with the following logs 
# docker logs xterm
ifelse: fatal: unable to exec /etc/s6/init-no-catchall/init-stage1: Permission denied
ifelse: fatal: unable to exec /etc/s6/init-no-catchall/init-stage1: Permission denied

Could you help me debbug.
What is different in your building process ?

**Comment by jlesage** [comment]
The way to build the baseimage against a new distro is to add a file to the `versions` directory.
But first, you need to build `jlesage/baseimage`.  For example, you could add `versions/ubuntu-14.04` with the following content:
```
DOCKERFILE=Dockerfile.debian
BASEIMAGE=i386/ubuntu:trusty
S6_OVERLAY_ARCH=amd64
```
Then build the baseimage:
```
./build ubuntu-14.04
```
Once done, you can build `jlesage/baseimage-gui` using a similar approach.  The version file in this case would have:
```
DOCKERFILE=Dockerfile.debian
BASEIMAGE=jlesage/baseimage:ubuntu-14.04
```

**Comment by bourgeoa** [comment]
That's  exactly what I did using, creating 'versions/ubuntu-14.04 with:
`DOCKERFILE=Dockerfile.debian`
`BASEIMAGE=i386/ubuntu:14.04`
`S6_OVERLAY_ARCH=ams64=`

and got all the problems listed above. that is why I went to rebuild your `ubuntu-16.04` and got all the same difficulties. My server is headless

**Comment by jlesage** [comment]
There is a typo in your `S6_OVERLAY_ARCH` variable.  Building `jlesage/baseimage` with the instruction I provided works fine for me.
Can you provide the full build output you have?

**Comment by bourgeoa** [comment]
Yes there is a typo here but not in `versions`
I join the full build of your ubuntu-16.04 no change what so ever
[baseimage ubuntu-16.04.txt](https://github.com/jlesage/docker-baseimage-gui/files/1887707/baseimage.ubuntu-16.04.txt)
I added the docker version output
Could the version be a problem. Is there a site where to build free images ?

**Comment by jlesage** [comment]
I have the exact same Docker version as you.  So I'm not sure why it doesn't work on Synology.  Are you building the image as root (using `sudo`)?  Or maybe you could try to build on another machine?
