### ISSUE TITLE
Enable dark mode for apps

### ISSUE THREAD

**Issue by eduarcor** [jlesage/docker-baseimage-gui#45]
Enable dark mode of linux in order to get the QT dark mode, and apps like mkvcleaver, mkvtoolnix, handbrake could trigger automatically dark mode.

**Comment by eduarcor** [comment]
You are probably right about openbox file manager, as is not based on QT or GTK, and just in C. There should be a way to put a dark theme on it and then the QT applications would try to mimic based on the colors of it.

**Comment by eduarcor** [comment]
You are probably right about openbox file manager, as is not based on QT or GTK, and just in C. There should be a way to put a dark theme on it and then the QT applications would try to mimic based on the colors of it.
But please, make this feature, light themes are killing my old eyes at night which is where I do most of the use of docker apps after work.

**Comment by eduarcor** [comment]
Any news about it? Please don't let this issue forgotten.

**Comment by eduarcor** [comment]
Any news about it? Please don't let this issue forgotten. It is very important for me and my eyes... :)

**Comment by jlesage** [comment]
As long as the issue is opened it won't fall into the cracks :)

I didn't had a lot of time to put on this and I didn't find yet the way to have applications switch to dark mode automatically.... :(

**Comment by eduarcor** [comment]
Any news @jlesage? It is being a long time

**Comment by eduarcor** [comment]
Bump

**Comment by acherubino** [comment]
Would love to see this +1

**Comment by PilaScat** [comment]
Bump

**Comment by IT-freak-Jake** [comment]
Bump

**Comment by jlesage** [comment]
Dark mode support added to v4 images.
