### ISSUE TITLE
Changing port from Environment Variables

### ISSUE THREAD

**Issue by eduarcor** [jlesage/docker-baseimage-gui#47]
As other tools from jlesage, it should be great to change the port from the Environment Variables.
I am using Docker inside of Synology DSM and is hard to do some configuration unless are exposed as variables.
I am using more applications from jlesage and I can't use them at the same time due to having the same port 5800 (like jdownloader) unless mapping ports, which I would like to avoid (although I know is possible).

**Comment by jlesage** [comment]
This is now possible with v4.0.0 images.

**Comment by eduarcor** [comment]
Awesome
