### ISSUE TITLE
x11vnc | ssvnc 'ReadExact: Socket error while reading'

### ISSUE THREAD

**Issue by dojo90** [jlesage/docker-baseimage-gui#5]
I can't connect to the server with encryption enabled.

using `Windows 10 64bit` and `SSNVC` ssvnc_windows_only-1.0.30.

I have opened a question on `SuperUser`: https://superuser.com/questions/1310970/x11vnc-ssvnc-readexact-socket-error-while-reading

**Comment by jlesage** [comment]
I have the same result as you.
The Window version seems to have problems.  The Linux version works correctly.
I will try to play more with it to see if there is any workaround...

**Comment by jlesage** [comment]
I finally got a working version.  See https://github.com/jlesage/docker-baseimage-gui#ssvnc
