### ISSUE TITLE
Update Documentation to Specify Remote Presence Port Requirement

### ISSUE THREAD

**Issue by JeffHochberg** [jlesage/docker-baseimage-gui#53]
The documentation specifies the ports you can use to access the web interface and the VNC server for the container, but I do not see anything that references the Remote Presence Port is that the container uses when it connects to connect to iDRAC 6.

You can see this value when you log into the iDRAC admin console and navigate to System -> Console/Media -> Configuration.

I changed the Remote Presence Port on my iDRAC6 controller in my Dell R410 Server to port 4900. I forget why I did it - it was a long time ago. The default value is 5900 per Dell's documentation.

Since the Remote Presence Port value is not exposed in your Docker container, when you try to connect via the container, the connection fails.

I changed the Remote Presence Port in iDRAC6 from 4900 back to the default 5900, and I was able to connect using the Docker container!!! This is AWESOME!

Great job! Please update the docs to reflect this as it's pretty important.

**Comment by jlesage** [comment]
Sorry but I have no idea what is an iDRAC6 and what is the Remote Presence Port.

Port `4900` is not used by the container.  Port `5900` is the one used to connect to the GUI using the VNC protocol, while port `5800` is used to connect to the GUI using the HTTP protocol.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
