### ISSUE TITLE
The UTF-8 fonts are not correctly displayed / installed.

### ISSUE THREAD

**Issue by PavelD** [jlesage/docker-baseimage-gui#55]
Hi,

I'm using `docker-jdownloader-2`, based on `docker-baseimage-gui`.

I have issue to see correct names of the packages / filenames in VNC.

![image](https://user-images.githubusercontent.com/447416/117495783-6034b200-af76-11eb-9a4c-81d2f81f12b4.png)

The first package name is in Japanese (no clue what it there) and the second has some wired characters in the name (source: https://www.youtube.com/watch?v=rD-nLlXSSxs).

What is missing in the configuration in this case?

**Comment by jlesage** [comment]
Did you try the `ENABLE_CJK_FONT` environment variable ?

**Comment by PavelD** [comment]
My bad, you're right! Problem solved.
