### ISSUE TITLE
x86 Version

### ISSUE THREAD

**Issue by t0mer** [jlesage/docker-baseimage-gui#57]
Hi,
I need to run WinScp on the container using wine. as for now WinScp is x86 based and can't be running
with  .x64 wine. 
Cheers

**Comment by jlesage** [comment]
Yes, I'm working on a new version that will be multi-arch.

**Comment by tomjamescn** [comment]
> Yes, I'm working on a new version that will be multi-arch.

please support arm64

**Comment by jlesage** [comment]
Images version 4.0.0 are now multi-arch.
