### ISSUE TITLE
Any hints on how to use this image with AppImage?

### ISSUE THREAD

**Issue by ovizii** [jlesage/docker-baseimage-gui#58]
I have used your base image to add my own prefered app to it and make it accessible via web ui and it works perfectly but now I found an app I would like to dockerize with your image but it is distributed in an "AppImage" format. 
https://appimage.org/ 

Apparently you download the app i.e. this one: https://www.fosshub.com/Shotcut.html?dwl=shotcut-linux-x86_64-210321.AppImage make it exectuable and run it. 

I'm just not sure if your base image supports this or if there is anything else I need to add to your base images.  

Any hints are very much welcome.

**Comment by jlesage** [comment]
Running the AppImage directly may not be easy.  It's probably easier to extract the content of AppImage and run the binary directly from there.

On the link you provided, there is a "Linux portable tar".  Did you try this one ?

**Comment by ovizii** [comment]
I had a look, that .txz file contains a .tar file which contains a .app file - is this really what I am looking for? Would I unpack, make executable and run that file?

Any more hints?

![image](https://user-images.githubusercontent.com/837902/125449926-41794277-9f74-4e3a-be22-7acbe745c9c6.png)

P.S. i saw they also have some "meager" instructions for building the app on your own, i might check that out, perhaps I can follow the instructions.

**Comment by ovizii** [comment]
I'm slightly overwhelmed by this app. I also had a look at openshot but it is using the same AppImage distribution type. 

Do you happen to have any idea for a video editor I can "easily" run via docker? No need for complicated tools, I just need basic functionality. 

Any hints are much appreciated. If not please feel free to close this ticket.

**Comment by ovizii** [comment]
I've been trying my hand at openshot, shotcut and flowblade but didn't get any results. 
Nothing to do with your base image, I guess its more my lack of skills. 
Anyway closing this ticket as there's nothing you can help me with :-)

**Comment by minecraftchest1** [comment]
@ovizii I normally install OpenShot using the Ubuntu repos. Any reason that wouldn't work for you?

**Comment by ovizii** [comment]
> @ovizii I normally install OpenShot using the Ubuntu repos. Any reason that wouldn't work for you?

I haven't tried that yet. Do you per chance have OpenShot running with one of these base images here?

**Comment by minecraftchest1** [comment]
I haven't tried openshot in any of the docker images. I can't see any reason why it wouldn't work though.
