### ISSUE TITLE
Request: FreeFileSync

### ISSUE THREAD

**Issue by zzatihz1** [jlesage/docker-baseimage-gui#60]
Not an issue but a request . . . I have been trying to use this image to create a Docker container for FreeFileSync. I am a Donation license user for FreeFileSync but the open source version of FreeFileSync would work just as well for me. FreeFileSync typically installs with an installer and I am having quite a few struggles installing it inside this image.

The end result I'm looking for is something similar to your Handbrake image which works perfectly.

Thank you in advance for any help. If not interested, please feel free to close this issue. Thanks again.

**Comment by zzatihz1** [comment]
That would be awesome! Thank you! Greatly appreciated!!!

**Comment by jlesage** [comment]
This is now available: https://github.com/jlesage/docker-freefilesync
