### ISSUE TITLE
npn not found when building linux/386 based on ubuntu-18.04-v3.0.0-pre.6

### ISSUE THREAD

**Issue by barbudor** [jlesage/docker-baseimage-gui#64]
Hi

I'd like to run a GUI based container on an old i386 machine running ubuntu-18.04.

Seeing that you have recently started to publish `jlesage/baseimage` beta images with linux/386 target, I tried to use `ubuntu-18.04-v3.0.0-pre.6` this way:
- copying `versions/ubuntu-18.04` to `versions/ubuntu-18.04-v3.0.0-pre.6` changing the tag from `ubuntu-18.04-v2.4.5` to `ubuntu-18.04-v3.0.0-pre.6`
- launching the build with `ubuntu-18.04-v3.0.0-pre.6` on the i386 machine

However, on the i386 machine itself, the build fails on 
https://github.com/jlesage/docker-baseimage-gui/blob/799f7c52011bee4a42b3c3749f2c604fa5c100e9/Dockerfile.debian#L143
with `'npm': No such file or directory`

On the amd64 machine, the build work but then fails when starting the tests as `bats` is not found.

I understand that you are in total rework of both baseimage and baseimage-gui so hopefully this feedback may help.
Let me know if more details would be usefull.
Maybe I should have used the v4 branch ?

Thanks for all this.

**Comment by jlesage** [comment]
Multi-arch images are not quite ready to be used, as development is not terminated yet.
But yes, `jlesage/baseimage:ubuntu-18.04-v3.0.0-pre.6` should be used with the v4 branch.
Note that I should start to publish pre-release versions of this v4 very soon.

**Comment by barbudor** [comment]
thanks.
looking forward updates

**Comment by jlesage** [comment]
Official v4 images now available.

**Comment by barbudor** [comment]
Thanks a lot
