### ISSUE TITLE
TS Muxer Nightly/ Upated Version

### ISSUE THREAD

**Issue by nc88keyz** [jlesage/docker-baseimage-gui#67]
It does not look like this docker has been updated in 3 years. Any possibility we can get leading edge or at least modern version of TS Muxer. [https://hub.docker.com/r/jlesage/tsmuxer](url)

**Comment by nc88keyz** [comment]
Correct, but the source code was turned over from the developer, and it has been alive and well for some time again if not mistaken: https://github.com/justdan96/tsMuxer and https://www.videohelp.com/software/tsMuxeR  seeing as there is a linux version. Could you update and add a nightly tag to your docker?  I honestly do not understand why more are not asking for this as it is a great tool to run as a docker on a NAS and speeds up transfer times from a desktop / laptop to and from a nas. I enjoy all of your dockers very much. Thank you!

**Comment by jlesage** [comment]
Let's track this in the proper repo: https://github.com/jlesage/docker-tsmuxer/issues/5
