### ISSUE TITLE
申请添加支持Freefilesync

### ISSUE THREAD

**Issue by gzxiexl** [jlesage/docker-baseimage-gui#69]
FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files. Instead of copying every file every time, FreeFileSync determines the differences between a source and a target folder and transfers only the minimum amount of data needed. FreeFileSync is Open Source software, available for Windows, macOS, and Linux.

https://freefilesync.org/

申请添加这个软件的docker镜像，谢谢

**Comment by jlesage** [comment]
Duplicate of #60.
