### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by MartinHotmann** [jlesage/docker-baseimage-gui#70]
Hi, I just had some thoughts about switching to a NAS with a ARM64 based CPU and quickly checked if I would be able to take over all my beloved docker containers/images. To my surprise, I noticed that (none?) of your images does support any ARM architecture. So I just wanted to start an open conversation about, if there are any plans to do so and if so, which of your images potentially could be candidates for this, since not all applications do have native ARM64 support.

I don't know about all applications, but here is a list of those which I think do already support ARM/ARM64:

FileZilla: https://forum.filezilla-project.org/viewtopic.php?p=175819#p175819
MakeMKV: https://forum.makemkv.com/forum/viewtopic.php?p=105912#p105912
MKVToolNix: https://mkvtoolnix.download/downloads.html#debian
tsMuxer: https://pkgs.org/download/tsmuxer (arm64 available)
FileBot: https://hub.docker.com/r/pfremm/filebot-docker/tags
Handbrake: should support it, as M1 support is given.

So most of the images I actually would need, are indeed having native ARM/ARM64 support. Would be cool if that could be implemented/supported in:

1. the baseimage
2. the images/applications itself

and then offered as multiple architectures like from some other docker image "makers" :)

If I said something stupid or missing something which states, that ARM64 support is already given - then please point ouit what I am missing :)

Thanks in advance!

**Comment by MartinHotmann** [comment]
Ah again I am too late to the party xD
https://github.com/jlesage/docker-baseimage-gui/issues/63

**Comment by jlesage** [comment]
A huge amount of work has been done on the baseimage to be a multi-arch image.  So yes, we should also start seeing soon multi-arch support for applications you mentioned :)

**Comment by jlesage** [comment]
Images version 4.0.0 are now multi-arch.
