### ISSUE TITLE
Replace x11vnc with TigerVNC for clipboard Unicode support and bump NoVNC version

### ISSUE THREAD

**Issue by sjtuross** [jlesage/docker-baseimage-gui#71]
According to https://github.com/LibVNC/x11vnc/issues/77, it looks like x11vnc doesn't support Unicode in clipboard.

NoVNC added support for full Unicode in clipboard since version 1.2.0. Hopefully bump it to the latest version 1.3.0.

I tested this image https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium-g3. Per it's [changelog](https://github.com/accetto/ubuntu-vnc-xfce-g3/blob/master/CHANGELOG.md), it uses TigerVNC 1.12.0 and noVNC 1.3.0. Clipboard can perfectly support Unicode.

This issue currently exists in all your great images as all are derived from this base image.

It will also address https://github.com/jlesage/docker-baseimage-gui/issues/43 and https://github.com/jlesage/docker-jdownloader-2/issues/46

**Comment by jlesage** [comment]
This is done with images v4.0.0.
