### ISSUE TITLE
Feature Request: Replace x11vnx and xvfb with TigerVNC to enable remote resize

### ISSUE THREAD

**Issue by baxerus** [jlesage/docker-baseimage-gui#8]
It would be great to replace x11vnc and xvfb with TigerVNC. This would allow resizing of the remote desktop accordingly to resizing the browser window (perhaps best with disable option e.g. by setting the width and height explicitly).

I would like the help in the process if you want to.

Is there something that directly speaks against this idea? Perhaps you already tried and have good reasons not to use TigerVNC?

Best regards

Benedict

**Comment by jlesage** [comment]
I evaluated a couple of solution and I remember having looking at TigerVNC.  However, I don't remember exactly why I didn't choose it.
One big benefit of x11vnc is that it natively supports websocket (used by noVNC), while other solutions need a websocket-to-tcp proxy.

**Comment by baxerus** [comment]
When I find time, I will try to get it running with TigerVNC + WebSocket Proxy like noVNC's Websockify

**Comment by baxerus** [comment]
@Zetten No, I'm sorry, I didn't manage to find the time to try it. But would still like to do it

**Comment by c64bob** [comment]
It seems x11vnc is in the process of adding support for remote resizing, see https://github.com/LibVNC/x11vnc/issues/91
