### ISSUE TITLE
Can we run full ubuntu gnome desktop in this ?

### ISSUE THREAD

**Issue by bolavefasfas** [jlesage/docker-baseimage-gui#80]
Can we run full ubuntu gnome desktop in this ?

**Comment by jlesage** [comment]
No, that's no the goal of this baseimage.

You can find other Docker images that implements full desktops.  For example: https://hub.docker.com/r/linuxserver/webtop

**Comment by jlesage** [comment]
Closing this issue. Please re-open if needed.
