### ISSUE TITLE
Running on Raspbian Lite Legacy (Buster)

### ISSUE THREAD

**Issue by CornHead764** [jlesage/docker-baseimage-gui#81]
Hello,

I'm trying to leverage this base image on my raspberry pi 4 which is currently running the 32bit version of raspbian (armhf), which from my understanding is equivalent to armv7. When launching the container, it seems to execute until it tries to start xvnc, at which point the container crashes with error code 132, which from what I can find, is an incompatible architecture error. Has anyone had any success running this on a raspberry pi? This seems to execute just fine on amd64. Unfortunately I do not have any arm64 devices to test on at the moment. 

Docker version 20.10.19, build d85ef84

`docker run jlesage/baseimage-gui:debian-10-v4

Unable to find image 'jlesage/baseimage-gui:debian-10-v4' locally

debian-10-v4: Pulling from jlesage/baseimage-gui

e4ea50bd37db: Pull complete 

4f4fb700ef54: Pull complete 

ebb3d9606ef0: Pull complete 

52e16641dee8: Pull complete 

5e430cf69c27: Pull complete 

18afc8c7dabe: Pull complete 

5de11e7a827b: Pull complete 

1ad616dbd7eb: Pull complete 

19248e04ed94: Pull complete 

bc4089a1f4d0: Pull complete 

dfe3400cf736: Pull complete 

37bb720c2e04: Pull complete 

3508932a1dbb: Pull complete 

a23bf134e13c: Pull complete 

4c466cf66662: Pull complete 

7c780694adb9: Pull complete 

e9b06065aaf8: Pull complete 

80fc75459426: Pull complete 

f87e558f0800: Pull complete 

86cd5f7c8f7c: Pull complete 

34c53c305fdb: Pull complete 

dc33f82a74df: Pull complete 

03ee8727400c: Pull complete 

09ded62e6f05: Pull complete 

f2297a6e5832: Pull complete 

Digest: sha256:c770b6226a558d4885efe400d4917e0afce8f515cc899a6089e630cc5bcc6d72

Status: Downloaded newer image for jlesage/baseimage-gui:debian-10-v4

[init        ] container is starting...

[cont-env    ] loading container environment variables...

[cont-env    ] APP_NAME: loading...

[cont-env    ] DISPLAY: executing...

[cont-env    ] DISPLAY: terminated successfully.

[cont-env    ] DISPLAY: loading...

[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...

[cont-env    ] GTK_THEME: executing...

[cont-env    ] GTK_THEME: terminated successfully.

[cont-env    ] GTK_THEME: loading...

[cont-env    ] HOME: loading...

[cont-env    ] QT_STYLE_OVERRIDE: executing...

[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.

[cont-env    ] QT_STYLE_OVERRIDE: loading...

[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...

[cont-env    ] XDG_CACHE_HOME: loading...

[cont-env    ] XDG_CONFIG_HOME: loading...

[cont-env    ] XDG_DATA_HOME: loading...

[cont-env    ] XDG_RUNTIME_DIR: loading...

[cont-env    ] container environment variables initialized.

[cont-secrets] loading container secrets...

[cont-secrets] container secrets loaded.

[cont-init   ] executing container initialization scripts...

[cont-init   ] 10-certs.sh: executing...

[cont-init   ] 10-certs.sh: terminated successfully.

[cont-init   ] 10-check-app-niceness.sh: executing...

[cont-init   ] 10-check-app-niceness.sh: terminated successfully.

[cont-init   ] 10-cjk-font.sh: executing...

[cont-init   ] 10-cjk-font.sh: terminated successfully.

[cont-init   ] 10-clean-logmonitor-states.sh: executing...

[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.

[cont-init   ] 10-clean-tmp-dir.sh: executing...

[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.

[cont-init   ] 10-fontconfig-cache-dir.sh: executing...

[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.

[cont-init   ] 10-init-users.sh: executing...

[cont-init   ] 10-init-users.sh: terminated successfully.

[cont-init   ] 10-jwm.sh: executing...

[cont-init   ] 10-jwm.sh: terminated successfully.

[cont-init   ] 10-nginx.sh: executing...

[cont-init   ] 10-nginx.sh: terminated successfully.

[cont-init   ] 10-vnc-password.sh: executing...

[cont-init   ] 10-vnc-password.sh: terminated successfully.

[cont-init   ] 10-web-data.sh: executing...

[cont-init   ] 10-web-data.sh: terminated successfully.

[cont-init   ] 10-x11-unix.sh: executing...

[cont-init   ] 10-x11-unix.sh: terminated successfully.

[cont-init   ] 10-xdg-runtime-dir.sh: executing...

[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.

[cont-init   ] 15-install-pkgs.sh: executing...

[cont-init   ] 15-install-pkgs.sh: terminated successfully.

[cont-init   ] 85-take-config-ownership.sh: executing...

[cont-init   ] 85-take-config-ownership.sh: terminated successfully.

[cont-init   ] 89-info.sh: executing...

    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮

    │                                                                      │

    │ Application:           DockerApp                                     │

    │ Application Version:   n/a                                           │

    │ Docker Image Version:  n/a                                           │

    │ Docker Image Platform: linux/arm/v7                                  │

    │                                                                      │

    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯

[cont-init   ] 89-info.sh: terminated successfully.

[cont-init   ] all container initialization scripts executed.

[init        ] giving control to process supervisor.

[supervisor  ] loading services...

[supervisor  ] loading service 'default'...

[supervisor  ] loading service 'app'...

[supervisor  ] loading service 'gui'...

[supervisor  ] loading service 'xvnc'...

[supervisor  ] loading service 'nginx'...

[supervisor  ] loading service 'certsmonitor'...

[supervisor  ] service 'certsmonitor' is disabled.

[supervisor  ] loading service 'jwm'...

[supervisor  ] loading service 'logmonitor'...

[supervisor  ] service 'logmonitor' is disabled.

[supervisor  ] all services loaded.

[supervisor  ] starting services...

[supervisor  ] starting service 'xvnc'...`

**Comment by jlesage** [comment]
I just tried with my Raspberry 4B running Raspberry OS 32 bit and the baseimage works fine.

Do you have the result with other images (Ubuntu, Alpine, ...) ?

**Comment by CornHead764** [comment]
Sparing you the wall of text, both alpine-3.15-v4.1.2 and ubuntu-20.04-v4.1.2 have the same result. loads until it attempts to start xvnc, then failed. running echo $? states the exit code is 132.

also double checked my architecture:
dpkg --print-architecture
armhf

I ran them again with CONTAINER_DEBUG set to 1, and it looks like we only get 1 additional line of relevant output.


[supervisor  ] all services loaded.

[supervisor  ] starting services...

[supervisor  ] starting service 'xvnc'...

[supervisor  ] started service 'xvnc'.

**Comment by jlesage** [comment]
What is the output of `uname -a` ?

Also, can you try to login to the container:
```
docker run --rm -ti jlesage/baseimage-gui:debian-10-v4 bash
```

And then manually run xvnc:
```
/opt/base/bin/Xvnc
```

**Comment by CornHead764** [comment]
uname -a returns:

Linux 3dprint 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

This is the pi I use to run my 3d printer, and I believe I used mainsailos, which is built upon raspbian lite 32bit. (https://docs.mainsail.xyz/setup/mainsail-os)

running the container in interactive mode with bash, and launching Xvnc appears to work as expected. Perhaps this is just a problem with the custom os provided by mainsail. If all else fails, I'll just rebuild this using a standard raspbian image and running mainsail myself without whatever customizations they included.
![image](https://user-images.githubusercontent.com/19508732/199345757-e6b694ea-2aed-41cd-a472-412602341c0c.png)

**Comment by jlesage** [comment]
It's very strange that Xvnc is running fine when launched manually.  So maybe it's the process supervisor that is crashing...

Is Docker itself up-to-date ?  And the OS ?

**Comment by CornHead764** [comment]
Debian 10, but all packages are up to date. 

Docker version 20.10.21, build baeda1f

**Comment by CornHead764** [comment]
As a bit of additional research, I was able to replicate the problem with a fresh install of mainsailos via the raspberry pi imager utility, and a fresh install of raspbian lite (legacy). mainsail is build upon raspbian lite legacy, which is the debian 10 build. 

The Debian 11 version of raspbian lite did work fine, as you also found. I am going to try upgrading from debian 10 to 11 and see if that resolves the problem. 

In every case, I am using the officially supported docker repo, with the install instructions documented: https://docs.docker.com/engine/install/debian/

**Comment by jlesage** [comment]
Thanks for the details.  I will have to try to replicate with Rasbian (Debian 10).  The difference might be the kernel...

Do you still have a device with Debian 10 installed ? If yes, I would be curious to know if issue is also seen with:
```
docker run --rm jlesage/baseimage:debian-10-v3
```

**Comment by CornHead764** [comment]
I do, I also found my spare raspberry pi 3b, so I can do additional testing on that as needed. Didn't want to risk that upgrade :)

Here is the output from the run of baseimage:debian-10-v3. Same result, but on 'app' instead of 'xvnc' 
![image](https://user-images.githubusercontent.com/19508732/199569669-fab5edc3-f696-4f32-a4b1-0c30e3b1b84f.png)

**Comment by jlesage** [comment]
I was able to reproduce and found the cause of the issue:  getting time via `clock_gettime(CLOCK_MONOTONIC)` was failing with `Operation not permitted`.  This seems to be a common problem with Raspberry Pi when this function is invoked in a Docker container with an "old" version of `libseccomp2`.

**Comment by jlesage** [comment]
A fix is on its way.

**Comment by jlesage** [comment]
Can you confirm the latest image works for you ?

**Comment by CornHead764** [comment]
Can confirm, it appears to be working now. Thanks!
