### ISSUE TITLE
10-nginx.sh: sed: unsupported command 5

### ISSUE THREAD

**Issue by T3553** [jlesage/docker-baseimage-gui#87]
docker command: 
docker run
  -d
  --name='FileZilla'
  -e TZ="Europe/Amsterdam"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="test"
  -e HOST_CONTAINERNAME="FileZilla"
  -e 'VNC_PASSWORD'='test'
  -e 'VNC_LISTENING_PORT'='5901'
  -e 'WEB_LISTENING_PORT'='-1'
  -e 'DARK_MODE'='1'
  -e 'USER_ID'='99'
  -e 'GROUP_ID'='100'
  -e 'UMASK'='000'
  -e 'APP_NICENESS'=''
  -e 'DISPLAY_WIDTH'='1980'
  -e 'DISPLAY_HEIGHT'='1080'
  -e 'SECURE_CONNECTION'='1'
  -e 'X11VNC_EXTRA_OPTS'=''
  -e 'INSTALL_EXTRA_PKGS'=''
  -v '/mnt/user':'/storage':'rw'
  -v '/mnt/user/appdata/FileZilla':'/config':'rw'
  'jlesage/filezilla:latest' 

container log:
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: Usage of INSTALL_EXTRA_PKGS environment variable is deprecated.  INSTALL_PACKAGES should be used instead.
[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.
[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-jwm.sh: executing...
[cont-init   ] 10-jwm.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: sed: unsupported command 5
[cont-init   ] 10-nginx.sh: terminated with error 1.

I think the problem is in [line 39](https://github.com/jlesage/docker-baseimage-gui/blob/eaef70771de84441ce7b03a186e1e7c89a2f0d38/rootfs/etc/cont-init.d/10-nginx.sh#L39) of nginx.sh

**Comment by jlesage** [comment]
Thanks for reporting this issue.  The fix will be part of the next release.

**Comment by jlesage** [comment]
Fixed with latest version.
