### ISSUE TITLE
New environment variable to control VNC compression

### ISSUE THREAD

**Issue by paya-cz** [jlesage/docker-baseimage-gui#92]
I am playing with your `jlesage/firefox` image by running it locally on my machine. I think the latency of the browser could be improved by disabling compression (since it is running locally after all). My suggestion is to add an environment variable to `jlesage/baseimage-gui` which would easily let users enable/disable VNC compression.

**Comment by jlesage** [comment]
The compression level can be controlled via the slider from the control menu.  Moving it all the way left sets a level of 0, which means no compression.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
