### ISSUE TITLE
Hide "noVNC_control_bar" when using the virtual keyboard?

### ISSUE THREAD

**Issue by Febtw** [jlesage/docker-baseimage-gui#94]
docker-baseimage-gui version: 4.3.6

When using the virtual keyboard, "noVNC_control_bar" blocks out some area of the page. 
But if I close the "noVNC_control_bar", the virtual keyboard is closed with it.

on my laptop Edge in emulate mode
![image](https://user-images.githubusercontent.com/96163355/218941589-2dbd2301-e8a7-491c-98dc-4b261f4d0922.png)

on ipad safari
![1](https://user-images.githubusercontent.com/96163355/218948965-c372c6a0-8e14-4822-a45d-253559f8146d.jpg)
</br>
</br>
I think the  noVNC of recent version is able to use the virtual keyboard and have "noVNC_control_bar" hidden.
The following noVNC is installed through ubuntu 20.04 repo last month, but I don't know how to find the version of it.
![1](https://user-images.githubusercontent.com/96163355/218956276-3265f6ac-9efe-46ff-90d0-c0adc5b13101.jpg)

![1](https://user-images.githubusercontent.com/96163355/218956291-12eef618-d251-47d8-9edc-1496f11ab907.jpg)

</br>
</br>
I have tried to update noVNC to 1.4.0 according [the Dockerfile of "docker-baseimage-gui"](https://github.com/jlesage/docker-baseimage-gui/blob/master/Dockerfile), but fail to use.

![image](https://user-images.githubusercontent.com/96163355/218951965-c6df4e98-69ca-4f6f-8eb0-ee4b76d5d417.png)
[Dockerfile.txt](https://github.com/jlesage/docker-baseimage-gui/files/10740101/Dockerfile.txt)

**Comment by jlesage** [comment]
So if I understand correctly you request, you would like the virtual keyboard to remain active when closing the control menu.
Do you see the same behaviour with version 4.2.2 of the baseimage?

**Comment by jlesage** [comment]
I was not aware of the new version of noVNC.  I will have to integrate it.

**Comment by Febtw** [comment]
> So if I understand correctly you request, you would like the virtual keyboard to remain active when closing the control menu. Do you see the same behaviour with version 4.2.2 of the baseimage?

Yes, I would like the virtual keyboard to remain active when closing the control menu.
And yes, I see the same behaviour with version 4.2.2 of the baseimage.

[Dockerfile with baseimage-gui 4.2.2.txt](https://github.com/jlesage/docker-baseimage-gui/files/10777045/Dockerfile.with.baseimage-gui.4.2.2.txt)

**Comment by jlesage** [comment]
Ok, I did more investigation on that and from what I understand, you should get this behaviour with both noVNC 1.3.0 and 1.4.0.  However, this behaviour can be easily adjusted, so the next version of the image will have the fix for that.

**Comment by Febtw** [comment]
> 

Thanks a lot!

**Comment by jlesage** [comment]
This should be fixed with version 4.4.0.

**Comment by Febtw** [comment]
> This should be fixed with version 4.4.0.

Yes, new version is good!
