### ISSUE TITLE
Add Setting for controlbar position on the right?

### ISSUE THREAD

**Issue by systemofapwne** [jlesage/docker-baseimage-gui#97]
Hello,
I would like to see a setting (e.g. via ENV_VAR) for having the control bar on the right. That should be done easily with CSS I guess.

The reason why I ask is, that I have your JDL2 container added into "organizr" (via iframes) and hitting the controlbar on the left sometimes makes me snap over to the organizr controlbar, that now covers JDL partially.
Here are some pictures of what I mean:
![image](https://user-images.githubusercontent.com/30482165/227791929-e67664bf-369f-42db-aef9-52185f0ffe70.png) ![image](https://user-images.githubusercontent.com/30482165/227792018-9ca2f3a7-7f39-4c6d-a5c7-6a9bd0d89e29.png)
Accidentally moving the mouse further to the left (first picture when moving the mouser like the red arrow) will popup the menu of organizr (second picture) that now covers JDL.
Allowing to move the control bar to the right would be a better UX.

**Comment by jlesage** [comment]
This is already possible: you can drag the handle to the right side.

**Comment by systemofapwne** [comment]
I am feeling so stupid for not having this tried out. Thank you so much. Consider my request as void.

**Comment by jlesage** [comment]
No worries!
